APP_KEY=base64:i3g6f+dV8FfsIkcxqd7gbiPn2oXk5r00sTmdD6V5utI=

DB_CONNECTION=mongodb
DB_HOST=mongodb
DB_PORT=27017
DB_DATABASE=laravel
DB_USERNAME=
DB_PASSWORD=

QUEUE_CONNECTION=redis
QUEUE_FAILED_DRIVER=null

REDIS_HOST=redis
REDIS_PASSWORD=
REDIS_PORT=6379
