APP_KEY=base64:i3g6f+dV8FfsIkcxqd7gbiPn2oXk5r00sTmdD6V5utI=

DB_CONNECTION=pgsql
DB_DATABASE=laravel
DB_HOST=db
DB_PORT=5432
DB_USERNAME=laravel
DB_PASSWORD=laravel

QUEUE_CONNECTION=redis

REDIS_HOST=redis
REDIS_PASSWORD=
REDIS_PORT=6379
